# Generated by Django 3.2.10 on 2022-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='session_end_year',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_start_year',
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
