# Generated by Django 3.2.10 on 2022-01-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
