# Generated by Django 3.2.10 on 2022-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'SchoolAdmin'), (2, 'Staffs'), (3, 'Students')], default=1, max_length=10),
        ),
    ]
