# Generated by Django 3.2.10 on 2022-02-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20220202_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_code',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject_title',
        ),
    ]
