# Generated by Django 3.2.10 on 2022-01-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20220116_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminHOD',
            new_name='Admin',
        ),
    ]
